name: Android Build on Push

permissions:
  contents: write

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      reason:
        description: Why did you trigger this workflow run manually?
        required: true
        default: Needing a new build.
        type: string
      tag:
        description: Which tag to build from?
        required: true
        default: v0.0.14
        type: string

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      WWWALLET_ANDROID_KEY_ALIAS: ${{ secrets.WWWALLET_ANDROID_KEY_ALIAS }}
      WWWALLET_ANDROID_KEY_PASSWORD: ${{ secrets.WWWALLET_ANDROID_KEY_PASSWORD }}
      WWWALLET_ANDROID_STORE_PASSWORD: ${{ secrets.WWWALLET_ANDROID_STORE_PASSWORD }}
      WWWALLET_ANDROID_STORE_B64: ${{ secrets.WWWALLET_ANDROID_STORE_B64 }}
      WWWALLET_ANDROID_HOST: ${{ secrets.WWWALLET_ANDROID_HOST }}

    steps:
      - name: Update ubuntu
        run: sudo apt-get update

      - name: Install Android SDK
        run: sudo apt-get install -y android-sdk

      - name: Try and find android build-tools
        run: apksigner

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Code Style
        run: ./gradlew ktlintCheck

      - name: Generate code style fixes
        if: failure()
        run: ./gradlew ktlintFormat

      - name: Suggest code style fixes
        if: failure()
        run: git diff

      - name: Test
        run: ./gradlew assemble check

      - name: Fingerprints
        run: ./gradlew checkFingerPrints

      - name: Run Connected Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          script: ./gradlew connectedCheck --stacktrace
